name: Telegram Forwarder

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  forward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install telethon

      - name: Run forwarder
        env:
          API_ID:    ${{ secrets.API_ID }}
          API_HASH:  ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SOURCE:    ${{ secrets.SOURCE }}
          TARGET:    ${{ secrets.TARGET }}
        run: python github_action_forward.py

      - name: Commit updated last_id
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_id.txt
          git commit -m "chore: bump last_id" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
